services:
  collab-backend:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://ajay:57ajay@db:5432/collabwrite?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
      - GO_REST_PORT=8081
      - GO_GRPC_PORT=9090
    depends_on:
      - db
      - kafka
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - collab-backend
  db:
    image: postgres:18beta3-alpine
    restart: always
    environment:
      - POSTGRES_USER=ajay
      - POSTGRES_PASSWORD=57ajay
      - POSTGRES_DB=collabwrite
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CLUSTER_ID=tCy5umSrQQG8JnGqOa1lPw
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  db_data:
  kafka_data:
